language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script: "mvn package"

notifications:
  email:
    recipients:
      - 'shout1233@gmail.com'
